from pydantic_settings import BaseSettings
from typing import Optional


class Settings(BaseSettings):
    """应用配置管理类，使用 Pydantic Settings 管理环境变量"""

    # 应用基础配置
    APP_NAME: str = "MindCanvas Backend"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # 服务器配置
    HOST: str = "0.0.0.0"
    PORT: int = 8000

    # 数据库配置
    DATABASE_URL: str = "postgresql://mindcanvas:mindcanvas@localhost:5432/mindcanvas"

    # 邮件服务配置（Resend）
    RESEND_API_KEY: str = ""  # Resend API Key
    EMAIL_FROM: str = ""  # 发件人邮箱地址（需要在 Resend 中验证）
    EMAIL_FROM_NAME: str = "MindCanvas"  # 发件人显示名称
    EMAIL_REPLY_TO: Optional[str] = None  # 回复邮箱地址（可选）

    # Redis 配置
    REDIS_URL: str = "redis://localhost:6379/0"

    # 加密密钥（用于 API Key 加密存储）
    ENCRYPTION_SECRET_KEY: str

    # JWT 配置
    JWT_SECRET_KEY: str = "your-jwt-secret-key-change-in-production"
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRE_MINUTES: int = 60 * 24 * 7  # 7 天

    # 日志配置
    LOG_LEVEL: str = "INFO"

    # 图片存储配置
    IMAGE_STORAGE_PATH: str = "/app/storage/images"
    IMAGE_BASE_URL: str = "http://localhost:8000/images"

    # 任务清理配置
    TASK_CLEANUP_INTERVAL: int = 3600  # 秒
    TASK_RETENTION_HOURS: int = 24  # 任务保留时间
    IMAGE_RETENTION_DAYS: int = 7  # 图片保留时间

    # API 速率限制
    RATE_LIMIT_PER_MINUTE: int = 60

    # 内容安全审核
    ENABLE_STRICT_AUDIT: bool = False

    # Google OAuth 配置
    GOOGLE_CLIENT_ID: str = "356898960552-aq7iv1iooas0ihn2j391becn9jvsuoou.apps.googleusercontent.com"

    # GitHub OAuth 配置
    GITHUB_CLIENT_ID: str = "Ov23li3PdYwr0zVzdJjw"
    GITHUB_CLIENT_SECRET: str = "8d5fcdddc76d312d937108c01450c13018301a07"

    # RSA 加密配置（用于 iOS 端 API Key 安全传输）
    # iOS 端使用此公钥加密 API Key，后端用私钥解密
    RSA_PUBLIC_KEY_BASE64: str = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEvSzFQdjhDMEpUSkk0WlpCZWRNRwo5QnFNN1RnVUhFNzI4TVZSb1MxaXMvdVdFbW1hQ0NZNVUwcmxGWHdQbGRUNkM5MG1CSndZV01HV01PeWMyeEY1CkVYbXhNakp6ZkdteVR5NndXUktQL1JIN0NRZEYxajdpMWxBSXdhcUF4RStQeEFTNm1ITnEwclIvdjZzV2NlQjYKSGVINXducTkzQ3ZsdWY4c3JoOTh5eG1ua2VCM0tCWStrMDZPNXdiN3N2KzN0MURVOTUzSHFjVktYc3NpQ2R2RAo1Y2hxNncxY2FHVTZRejlNN3lnV2lOMU9BSlRQNlQrZnAxSmxwbmhXUEMrSWw0ME9RcGNBRnVMZmd2QTZmeDd0CjVNeUE1RWxnaXd5bHE3R0NMVlNRWEZDWHRvWHFnTXhqSWpLM1BCU2FIbllmOWhUaWlHb2lEKzhydm4xQUpBUGIKbFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
    RSA_PRIVATE_KEY_BASE64: str = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRDhyVSsvd0xRbE1ramgKbGtGNTB3YjBHb3p0T0JRY1R2Ynd4VkdoTFdLeis1WVNhWm9JSmpsVFN1VVZmQStWMVBvTDNTWUVuQmhZd1pZdwo3SnpiRVhrUmViRXlNbk44YWJKUExyQlpFby85RWZzSkIwWFdQdUxXVUFqQnFvREVUNC9FQkxxWWMyclN0SCsvCnF4Wng0SG9kNGZuQ2VyM2NLK1c1L3l5dUgzekxHYWVSNEhjb0ZqNlRUbzduQnZ1eS83ZTNVTlQzbmNlcHhVcGUKeXlJSjI4UGx5R3JyRFZ4b1pUcERQMHp2S0JhSTNVNEFsTS9wUDUrblVtV21lRlk4TDRpWGpRNUNsd0FXNHQrQwo4RHAvSHUza3pJRGtTV0NMREtXcnNZSXRWSkJjVUplMmhlcUF6R01pTXJjOEZKb2VkaC8yRk9LSWFpSVA3eXUrCmZVQWtBOXVWQWdNQkFBRUNnZ0VBRTduWUJhbEpVYlMrUklEb0lGYnkyUVc2OE1pMXBvd2M4bjVhWkJIWXFIZkEKcHpQLy9CamlnQ0o5c0pLeDNoNzFYUTIrYW1lMm1EU1hiQlJjeVN3YnM5czRrOVJQemNFQlZFc3ZKZXBjRVZsaApBV1hFU2FNNUx1Ly83d0ZIbk9FZjRTRlpZVGpKZUhwSGxZZ0pjRFIzeVhOd2ZkZjZrSUMySmpJZlRvSCtIOERRCjdSTE8wcGc5bnAxYnYwSGwyeWFxdnE3VDFJR1ZYaWFwYjlxTmJJQXNDK3EyUUpHSUpieVBxdWtWZndSZWFyTDEKdTZjZjJjUmxNdDcyWjRFaEM5My9peDVHU1c0MVFWK0RIK2RESlJKS1pYTGlFaFM5MjdtdXoyRjk3c2ErVGNxMgpRZ1QzMG1ZUGY0ME9wVXM0TkttMnVoSGQxM2Q4YUxnT25HaUZBdllvZFFLQmdRRC9ScnYzcW8xS3BOendrQUt3CjhOb3BhT2c4Yi8xOXJqSnJicWM5Rm94aXgzVFpwcTRkZjVxY0syVTh1R0lieWNkZ0R4NGlWMWxYcWQ4SzBpdFMKaDNsVFpLdUtSYlNxc0lJaGx5Y2VvK0NhMGE4TFRzdWVvejlQbXB2TXB2QXVpc3A3cmsyMjhMSUtjNnhWNjRwNwpQZEpPSmIrNWQ1MDFJd09MWm03ZWYzdFAyd0tCZ1FEOVpMRGFqVmZYSGpaa0x5T29xQkdMK0c5Z0FZYXRUT252CjZHS2IxQ2h3MTRtdVczTUtjUkgvbXlpRUR2d2xoZzh2dGEyS3lLU2l5ckNFcHc3MWk4TjJvOG1jamJKSUUvYTkKdDM3V0tBOWVGRE91dmt2b2VmYUo5NmJIMTJJTEI0L1FYK3ZKdUFFSWozbVQ2cWdadG9mTDlDbDNoWldiMXlvMApaTFZ1R0IvVlR3S0JnQjRJRmtqMnVaU1VmS0dZYjVpZFhTME4rSFJUd0lDdW82UGI2clRYR0VEdXNpS0E1MjcwCitoMXhSWUcxTjJXSmdYa2RqakFBRXJTcmVWL3VoY1k1eGQ0M3M2NmFzTHg3ODNNOE13LzV1NHk3S2xxc05Hdy8KVEUxekpPMFlucHo3R3dNZDZHcWpPbTdjV09QcXgrbmp4Z0FIbE55ZTQ5SENnc0k5bE1GOFFlZU5Bb0dBUHZUMApoK2lVU1l0bElqRWdIL2hhRzdmSEhFaGt5TXdTVjV3YVcvTXpkUTNvVkZ5K1VYclVhUGlJOFg2em9UTVV0TnJqCjJsYU5xVERJK0x4MUdBYjRzcEp4TmlkeWd6d0trd3B6Umd3Ly9UVHh2bG5qakVnNVBBQSsvT29EbncvcTZHL2MKcW9yQUh2dGV6cVIvelp1dlU3by9UMFh1YlFEaHFKRFpEeGlKV0RzQ2dZQi8yd08zUWVtK1MxWkFzRmRJcGVvRAp0bFNNWkJEV2labWNRS3A1T1VEN204cVlnZUFUSXY2T3cxbExYaFJXYTRKbkI2TDNramM4RS9ualUxcTRVc0pXCi9Xc2NOSko3TGI3dThGa21lRDBnZzRhVEZiNmNVRmcvVTFYaWV4UzhIZllTeC9lZ3dNVHg0YnNsM0pxMFBWdFMKUkhTRFYyZVZKQmQ5NUdEdTFoUVM3Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = True


# 全局配置实例
settings = Settings()